spring:
  application:
    name: nachrichtenproxy
  profiles:
    active: usage_message
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 30000